import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-ai-report-modal',
    standalone: true,
    imports: [CommonModule],
    template: `
    <div class="fixed inset-0 bg-slate-900/70 backdrop-blur-md z-[60] flex items-center justify-center p-6">
      <div class="bg-white rounded-[2.5rem] shadow-2xl w-full max-w-4xl overflow-hidden border border-slate-200 flex flex-col max-h-[90vh] animate-in fade-in zoom-in duration-300">
        <!-- Header -->
        <div class="px-10 py-8 border-b border-slate-100 flex items-center justify-between bg-purple-50/50">
          <div class="flex items-center gap-4">
             <div class="w-12 h-12 bg-gradient-to-tr from-purple-600 to-indigo-600 rounded-2xl flex items-center justify-center text-white shadow-xl shadow-purple-200">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-7 h-7">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                </svg>
             </div>
             <div>
                <h2 class="text-2xl font-black text-slate-900 tracking-tight">AI Network Intelligence Report</h2>
                <div class="flex items-center gap-2 mt-1">
                   <span class="text-[10px] font-bold uppercase tracking-widest text-purple-600">Generated by Gemini 1.5 Pro</span>
                   <span class="w-1 h-1 bg-slate-200 rounded-full"></span>
                   <span class="text-xs text-slate-400">Senior NOC Persona Active</span>
                </div>
             </div>
          </div>
          <button (click)="close.emit()" class="text-slate-400 hover:text-slate-600 p-3 rounded-2xl hover:bg-white transition-all">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6m-12 0l12 12" />
            </svg>
          </button>
        </div>

        <!-- Content -->
        <div class="flex-1 overflow-y-auto p-10 prose prose-slate max-w-none prose-headings:text-slate-900 prose-strong:text-slate-900 prose-p:text-slate-600 prose-li:text-slate-600 custom-scrollbar">
           <div class="whitespace-pre-wrap font-sans leading-relaxed">
              {{ report() }}
           </div>
        </div>

        <!-- Footer -->
        <div class="px-10 py-6 border-t border-slate-100 flex items-center justify-between bg-slate-50">
           <p class="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-none">Confidential Automated Network Audit</p>
           <button (click)="close.emit()" class="px-8 py-3 bg-slate-900 text-white rounded-2xl text-sm font-bold shadow-lg hover:shadow-xl transition-all active:scale-95">
              Acknowledged
           </button>
        </div>
      </div>
    </div>
  `,
    styles: [`
    .custom-scrollbar::-webkit-scrollbar { width: 6px; }
    .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
    .custom-scrollbar::-webkit-scrollbar-thumb { background: #e2e8f0; border-radius: 10px; }
  `]
})
export class AiReportModalComponent {
    report = input.required<string>();
    close = output<void>();
}
